### ISSUE TITLE
doesnt save vehicles in the database

### ISSUE THREAD

**Issue by mifsopo** [HumanTree92/esx_eden_garage#10]
it will only save 1 vehicle for the entire server once a vehicles is saved no one can save any vehicles at all i cant submit the error as text because i cant copy my console 
![dup](https://user-images.githubusercontent.com/44308680/47250002-51eb0e80-d3e9-11e8-8c15-138959209dc0.PNG)
![sqlerror](https://user-images.githubusercontent.com/44308680/47250005-59aab300-d3e9-11e8-8477-90b44e815494.PNG)

figured out how to get it as text 

> [ERROR] [MySQL] An error happens on MySQL for query "INSERT INTO owned_vehicles (vehicle, owner) VALUES (@vehicle, @owner) {@owner=steam:11000010ab7cf74;@vehicle={"modRightFender":-1,"modTank":-1,"modSeats":-1,"modHood":-1,"m
odSuspension":-1,"color1":0,"modAirFilter":-1,"modStruts":-1,"health":1000,"modXenon":false,"modLivery":-1,"modFrontWheels":-1,"modTrimA":-1,"modArchCover":-1,"modHorns":-1,"modWindows":-1,"modBackWheels":-1,"modOrnaments":-1
,"modFrontBumper":-1,"modShifterLeavers":-1,"modFrame":-1,"neonColor":[255,0,255],"plateIndex":0,"modFender":-1,"modVanityPlate":-1,"windowTint":-1,"dirtLevel":5.0,"modTransmission":-1,"color2":4,"modTurbo":false,"modAerials"
:-1,"modSideSkirt":-1,"tyreSmokeColor":[255,255,255],"modSpeakers":-1,"modTrimB":-1,"modRearBumper":-1,"modEngine":-1,"neonEnabled":[false,false,false,false],"modTrunk":-1,"wheels":5,"modDoorSpeaker":-1,"modSteeringWheel":-1,
"plate":"05ZOF713","model":1549126457,"modHydrolic":-1,"modDial":-1,"modPlateHolder":-1,"modSpoilers":-1,"modAPlate":-1,"modEngineBlock":-1,"pearlescentColor":5,"modSmokeEnabled":false,"modRoof":-1,"wheelColor":112,"modDashbo
ard":-1,"modGrille":-1,"modArmor":-1,"modBrakes":-1,"modExhaust":-1}}": Duplicate entry '' for key 'PRIMARY' 

>

**Comment by mifsopo** [comment]
i understand it says duplicated key for primary but i dont understand how to fix that

**Comment by HumanTree92** [comment]
Is the car dealer job buying the vehicle or the player?

**Comment by mifsopo** [comment]
what do you mean?the car dealership sells the car if thats what you mean

**Comment by mifsopo** [comment]
what you linked maked no sense to me, i dont know what newest "source code" is
