### ISSUE TITLE
[FIXED] i fixed my vehicle shop issue but now its garage sided

### ISSUE THREAD

**Issue by mifsopo** [HumanTree92/esx_eden_garage#11]
so i can buy vehicles just fine (i had to fuly reinstall both garage and vehicle shop) but now ewhen i store them they go straight to the impound and i get this error

> [ERROR] [MySQL] An error happens on MySQL for query "UPDATE owned_vehicles SET state =@state WHERE plate=@plate {=}": Unknown column 'state' in 'field list' 

i havnt edited the database yet bc i dont want to mess anything up more than it is

![new plate](https://user-images.githubusercontent.com/44308680/47261472-0e9ea780-d49e-11e8-8b09-5eee3b9ef051.PNG)

**Comment by mifsopo** [comment]
EDIT: i fixed it by adding the state row, thanks anyways!! <3

**Comment by younesskhinit** [comment]
ALTER TABLE `owned_vehicles` ADD `state` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'State of the car' AFTER `owner`;

**Comment by mifsopo** [comment]
in owned_vehicles i right clicked added new table,  named it state-TINYINT-1- default of 0 (number zero)

below is an image of my new owned_vehicles table 
![new plate](https://user-images.githubusercontent.com/44308680/47267630-890a0e80-d514-11e8-8e5d-504663999cca.PNG) 
Hope this helped @rxduu

**Comment by HumanTree92** [comment]
If u don't mind me asking is a Car Dealer selling the vehicle & then your storing it?
