### ISSUE TITLE
Getting car at fork, getting NIL error in server log

### ISSUE THREAD

**Issue by ForthtuN** [HumanTree92/esx_eden_garage#12]
Sometimes we can't take out vehicles from the fork.
Some examples what happend

I set myself as car dealer, sell the car to my friend, he goes with it to the garage, puts it in, and when he tries to get it out he can't and it says he needed to go to the fork strange enough. 

Then when we were there he couldn't get it out from the fork. He did see the vehicle in the fork menu but couldn't get it. So he spammed it alot and suddenly it went out.

Are there any error somewhere? Is it zap-hosting having slow mysql or what can it be?

We then went to the fork and tested both of us with a car we owned and sometimes we got it out and sometimes not. Even if the car was "state 0" in owned vehicle in sql and we see it in the fork menu we can't sometimes get it out. And then all of a sudden you can. Also getting this message in the server log sometimes when we try

"UPDATING STATE 
CZF 536 
UPDATING STATE 
nil 
UPDATING STATE 
nil 
UPDATING STATE 
CZF 536 
UPDATING STATE 
CZF 536 
UPDATING STATE 
nil 
UPDATING STATE 
CZF 536"

CZF 536 being the plate number.

**Comment by HumanTree92** [comment]
From what i know so far is this garage system does not like it when a Car Dealer sells the vehicle to someone else. Not sure why. Also by fork you mean impound lot. But if your spamming the key & its not taking it out from the impound lot or list it does seem like mysql is being slow.

**Comment by ForthtuN** [comment]
Ah okey. Yes im afraid of that, been hearing that zaphosts mysql isn't so. Maybe it could be that.

**Comment by twistedcinema** [comment]
I am having the same issue with this ForthuN  Ive been messing with stuff attempting to fix this but no luck so far. Its not just this garage as it does this with all of them. I had to disable playermanagement for it to work properly.

**Comment by HumanTree92** [comment]
As for now i see this has to do with something from the Car Dealer Job & not this. I haven't been able to find a way to fix this but will continue trying in the Future when i have time.
