### ISSUE TITLE
Return infinite vehicles

### ISSUE THREAD

**Issue by MorreJaa** [HumanTree92/esx_eden_garage#14]
Hello everyone, I have a problem with this script, I’ve seen other servers with it, and on the other servers I can get more than one vehicle from the garage and on my server it does not work, it only lets you take a vehicle if you have a vehicle outside the garage will not let me take another … any help me?

**Comment by HumanTree92** [comment]
This sounds similar to a recent thing i have discovered. Say you have 6 cars owned in the garage you will only be able to take out around half of them at the same time. The more cars you own the more you can take out at the same time.
