### ISSUE TITLE
SQL Execute error

### ISSUE THREAD

**Issue by BrasX** [HumanTree92/esx_eden_garage#17]
i have this error massage:

[SQL] Query eden_garage start
[ERR] 1060 - Duplicate column name 'state'
[ERR] ALTER TABLE `owned_vehicles` ADD `state` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'State of the car' AFTER `owner`;
[SQL] Finished with error

i try 2 delete "column" but i cant "Access denied for user 'Zap******-*'

**Comment by HumanTree92** [comment]
This sounds like an issue with your DB not this script.
