### ISSUE TITLE
cannot store motorcycle

### ISSUE THREAD

**Issue by Betonejro** [HumanTree92/esx_eden_garage#4]
Hello, I have problem with store motorcycles. When I'm in delete point and try delete vehicle, I see cannot_store_vehicle information ;/

**Comment by HumanTree92** [comment]
Do you own the Motorcycle? I just checked it & i am able to buy a motorcycle & store it. Then pull it out & store it again.

**Comment by HumanTree92** [comment]
Also did you make sure you updated your owned_vehicles to the new DB?

**Comment by Betonejro** [comment]
This is owned_vehicles from esx_vehicleshop (updated 8 days ago)
`CREATE TABLE `owned_vehicles` (
	`owner` varchar(30) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,

	PRIMARY KEY (`plate`)
);`

It's my DB 

`CREATE TABLE `owned_vehicles` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`owner` varchar(30) NOT NULL,
        `state` BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'State of the car',
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,

	PRIMARY KEY (`id`)
);`

Because when I don't have primary key id i have this error 

> [ERROR] [MySQL] An error happens on MySQL for query "UPDATE owned_vehicles SET state =@state WHERE id=@id {@state=False}": Unknown column 'id' in 'where clause'


Now I try storage other motors, and only AKULA have problem ;/

**Comment by HumanTree92** [comment]
Well that MySQL error isn't from this script. Try a fresh copy of this script. No where in the server/main.lua is anything that has UPDATE owned_vehicles SET state =@State WHERE id=@id {@State=False}. You can even check for yourself. I just tried the Akuma and its working for me just fine.
