### ISSUE TITLE
Multiple Properties: Private Garages Bug

### ISSUE THREAD

**Issue by HumanTree92** [HumanTree92/esx_eden_garage#5]
Property Bug WIP.

`[ERROR] [MySQL] An error happens on MySQL for query "SET @ownedProperties = (SELECT name FROM owned_properties WHERE owner=@identifier);SET @gateways = (SELECT gateway FROM properties WHERE name = @ownedProperties AND gateway IS NOT NULL);SELECT name FROM properties WHERE name = @ownedProperties AND gateway = @gateways OR name = @gateways AND gateway IS NULL OR name = @ownedProperties AND gateway IS NULL; {@identifier=steam:1100001077f49e5}": Subquery returns more than 1 row`

**Comment by HumanTree92** [comment]
If anyone knows a fix for this let me know.

**Comment by manups4e** [comment]
MySQL.Async.fetchAll cannot have SET command afaik..

**Comment by HumanTree92** [comment]
@manups4e  I've been going over this & i am probably over thinking this.

**Comment by HumanTree92** [comment]
This has been fixed.
