### ISSUE TITLE
3 Bugs that I Found

### ISSUE THREAD

**Issue by 1stLT** [HumanTree92/esx_eden_garage#8]
I found 3 bugs in this script:

When storing vehicles without enough money, it will take the money anyway, and put me in minus.

When storing vehicles and taking them from the impound lot, they are being duplicated if stored again.

If trying to unowned vehicles, the vehicles just disappear instead of showing an error notification.

Hope you'll fix those soon.

**Comment by HumanTree92** [comment]
1. This is normal. Will try to instead to take money from the bank if no cash in hand.
2. Not sure how this is happening. From what i am getting is that your stating that if i buy a vehicle & store it i can go to the impound lot & pull it out. I have tested this myself & if the vehicle is stored its not showing up in the impound list. But i have noted in the readme that if you pull a vehicle out of the garage you can go to the impound and pull a dup of it. But if you sell 1 of them it removes it from the db of owned_vehicles.
3. Not really an issue. Just don't pull an unowned vehicle into the garage.
